#Creado por David Zometa
#Fecha 20-07-26
#Contenedor Tipo Proxy y App NodeJs
services:
#servicio 1 con el nombre de proxy  
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eks-proxy
    ports:
      - "80:80"
    networks:
      - red-eks2
    restart: unless-stopped
    
# Servicio 2 con el aplicativo 
  app:
    build: 
      context: ./APP

      dockerfile: Dockerfile_dev  #Utilizando un archivo Personalizado de Dockerfile_dev
    container_name: eks-app
    expose:
      - "3000"

#Rutas de volumnenes del aplicativo     
    volumes:
      - ./APP:/app 
      - /app/node_modules


    networks:
      - red-eks2
    restart: unless-stopped

networks:
  red-eks2:
    external: true  
